### ISSUE TITLE
error when install app - pip install django-timelinejs

### ISSUE THREAD

**Issue by almerindo** [abdallah/django-timelinejs#15]
E:\PYTHON\envs\prj_zaptime>pip install django-timelinejs
Collecting django-timelinejs
  Downloading https://files.pythonhosted.org/packages/b2/62/584ee1eca82db36886cff3566615d5a1343dc9d067144d56ad9687f76adc/Django-TimelineJS-0.2.tar.gz (238kB)
    100% |████████████████████████████████| 245kB 715kB/s
 
Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\almer\AppData\Local\Temp\pip-install-r3bvnf7i\django-timelinejs\setup.py", line 44
        print 'files', files
                    ^
    SyntaxError: Missing parentheses in call to 'print'. Did you mean print('files', files)?

**Comment by dolugen** [comment]
Hi @almerindo You should have better luck with the trunk version. That looks like some... outdated stuff.
